version: 2
jobs:
  green-job:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run: go get -u github.com/raviqqe/muffet
      - run: bash portfolios/jakubtajovsky.sh
      
workflows:
  version: 2
  build_and_test:
    jobs:
      - green-job
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - green-job
